import React from 'react';

const LiveDemo = () => {
  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <div className="bg-white p-8 rounded-xl border border-gray-200 shadow-sm">
        <h2 className="text-2xl font-outfit font-bold text-navy-800 mb-4">⚡ Live Demo Playground</h2>
        <p className="text-gray-600">This page will host a playground allowing users to submit live transaction metrics, run CatBoost inference, and obtain live explanations generated by Claude.</p>
      </div>
    </div>
  );
};

export default LiveDemo;
